name: Create and Upload Artifact

on:
  push:
    branches:
      - main

jobs:
  check_runner:
    runs-on: macOS
    env:
      RUNNER_NAME: "macOS"
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Text File
        run: echo "This is a sample text artifact." > my_artifact.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: my_artifact.txt

      - name: Checkout
        uses: actions/checkout@v3
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: my_artifact.txt
          tag_name: v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
