name: Create and Upload Artifact

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  check_runner:
    runs-on: macOS
    timeout-minutes: 1
    steps: 
      - name: runner test
        run: echo "I am alive"

  build:
    runs-on: ${{ github.event.workflow_run.workflow_job.conclusion == 'failure' && 'ubuntu-latest' || 'macOS' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Text File
        run: echo "This is a sample text artifact." > my_artifact.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: my_artifact.txt

      - name: Checkout
        uses: actions/checkout@v3

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
