name: Create Text Artifact

on:
  push:
    branches:
      - main

jobs:
  create_artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Text File
        run: echo "This is a sample text artifact." > my_artifact.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: my_artifact.txt
