name: Print Text Artifact

on:
  workflow_run:
    workflows: ["Create Text Artifact"]
    types:
      - completed

jobs:
  print_artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact from Release
        id: download_artifact
        run: |
          # Download the artifact from the release using the GitHub API
          curl -sSL -o my_artifact.txt \
            "https://api.github.com/repos/${{ github.repository }}/releases/latest/assets?name=my_artifact.txt" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
          if [ $? -ne 0 ]; then
            echo "Failed to download artifact."
            exit 1
          fi

      - name: Print Artifact Content
        run: cat my_artifact.txt