name: Print Text Artifact

on:
  workflow_run:
    workflows: ["Create Text Artifact"]
    types:
      - completed

jobs:
  print_artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact

      - name: Print Artifact Content
        run: cat my_artifact/my_artifact.txt
