name: Print Text Artifact

on:
  workflow_run:
    workflows: ["Create Text Artifact"]
    types:
      - completed

jobs:
  print_artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Print Release Tag
        run: |
          # Get the release tag from the GitHub context
          release_tag=${{ github.event.release.tag_name }}
          echo "Release Tag: $release_tag"