name: Verified Transition

on:
  workflow_dispatch:

jobs:
  verified_transition:
    runs-on: macOS
    steps:
      - name: Check User
        run: |
          allowed_users=("pmuraus" "mihahoz")

          # Check if the triggerer's username is in the allowed_users list
          if [[ ! " ${allowed_users[@]} " =~ " ${GITHUB_ACTOR} " ]]; then
            echo "This workflow can only be triggered by approved users."
            exit 1
          fi

      - name: Get archived release fix version
        uses: actions/download-artifact@v2
        with:
          name: fix-version-artifact

      - name: Read archived release fix version
        run: cat fix-version-artifact.txt