name: Print Text Artifact

on:
  workflow_run:
    workflows: ["Create Text Artifact"]
    types:
      - completed

jobs:
  print_artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact

      - name: Print Artifact Content
        run: cat my_artifact/my_artifact.txt
      
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: my_artifact.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}